# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [4]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(6,11)

In [2]:
arr_1

array([0, 1, 2, 3, 4])

In [5]:
arr_2

array([ 6,  7,  8,  9, 10])

In [6]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10])

In [10]:
# Vertical stacking - Increasing the number of row
np.vstack((arr_1,arr_2))

# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))
arr_3

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [11]:
# Checking the dimensions of the array
arr_3.ndim

2

In [12]:
# Printing the created array
arr_3

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [13]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [20]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [22]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [23]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40)
arr_6 = arr_6.reshape(5,4)
# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [27]:
# Stacking arr_5 and arr_6
np.hstack((arr_5,arr_6))

array([[ 1,  2, 20, 21, 22, 23],
       [ 3,  4, 24, 25, 26, 27],
       [ 5,  6, 28, 29, 30, 31],
       [ 7,  8, 32, 33, 34, 35],
       [ 9, 10, 36, 37, 38, 39]])

In [28]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [30]:
arr_5.shape

(5, 2)

In [32]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = arr_6.reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [33]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [41]:
x=np.arange(1,133)

In [42]:
x = x.reshape(11,12)

In [43]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
       [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [ 49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72],
       [ 73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96],
       [ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108],
       [109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132]])

In [45]:
np.unravel_index(99,(11,12))

(8, 3)

In [46]:
a = np.arange(1,3*3+1)

In [81]:
b = np.arange(11,14)

In [82]:
a = a.reshape(3,3)

In [83]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
c = np.vstack((a,b))

In [85]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [86]:
d = np.arange(21,25)

In [88]:
d

array([21, 22, 23, 24])

In [98]:
d.shape

(4,)

In [102]:
e=np.transpose(d,(4,1))
e

ValueError: axes don't match array

In [95]:
np.hstack((c,e))

array([[ 1,  2,  3, 21],
       [ 4,  5,  6, 22],
       [ 7,  8,  9, 23],
       [11, 12, 13, 24]])