In [1]:
import numpy as np

In [44]:
x = np.ones((9,9), dtype='int')
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [45]:
x[1:-1,1:-1]=0
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [39]:
np.ones((3,3), dtype='int')


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
a = np.array([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
a

array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [60]:
b=a[1,:]
b

array([5, 7, 0])

In [61]:
c=a[2,:]
c

array([9, 9, 3])

In [52]:
a[1,:]=c

In [53]:
a

array([[4, 3, 1],
       [9, 9, 3],
       [9, 9, 3],
       [8, 2, 4]])

In [54]:
a[2,:]=b

In [55]:
a

array([[4, 3, 1],
       [9, 9, 3],
       [9, 9, 3],
       [8, 2, 4]])